name: Publish NPM package

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
      - v*.*.*-*-*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: npm version --allow-same-version --no-git-tag-version $(git describe --tags)

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
